### ISSUE TITLE
Have a way for a player to reopen the breaktime window, if accidentally closed, while still active by GM

### ISSUE THREAD

**Issue by kiloforce** [ironmonk88/breaktime#12]
If a player gets over excited and closes the window, there is no way for the player to reopen the breaktime window.  Maybe the window should minimize instead of close?  Or have a button to reopen it, while the GM still has it activated?

**Comment by ironmonk88** [comment]
Latest version, the breaktime button should appear on the players listing for players when the game is in break time.  So if they close the window they can re-open it using that link.
