### ISSUE TITLE
Compatibility with SmallTime snapped to Player List

### ISSUE THREAD

**Issue by apoapostolov** [ironmonk88/breaktime#16]
The size expansion of the Player List is not available to SmallTime for some reason causing it to overlap when Player List is being resized (expanded and closed).

![image](https://user-images.githubusercontent.com/4083812/170979631-353ab6c4-f18f-4fd5-b07a-3997b44a8758.png)

**Comment by ironmonk88** [comment]
Closing this as it looks like smaltime fixed it.
