### ISSUE TITLE
Sound Alert,Rdy Check.

### ISSUE THREAD

**Issue by kimetmx** [ironmonk88/breaktime#20]
Hello!!! 
Is it possible that when the popup appears to the players, something sounds to them? just to get their attention if they are close but not paying attention to the screen, something like a redy check. (world of warcraft redy check ride).
(players get lost on the phone, only noise wakes them up).
I hope to be able to support you soon, thanks for your work.

**Comment by ironmonk88** [comment]
Added to the latest release.
