### ISSUE TITLE
[BUG] the brb button doesnt update on forge.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [ironmonk88/breaktime#21]
**Describe the bug**
the brb button doesnt update on forge as it does in comparison to being run on a home client. the logo for when it says its away doesnt update to say they are back

**To Reproduce**
1. Go to click on the button on the left to step away whilst being on a forge server
2. Click on the button again and it doesnt update

**Expected behavior**
i expect it to update and display that the player has returned.

**Screenshots**

**Please complete as much of the following information as possible:**
 - Browser chrome
 - Foundry Version v10.291
 - System pathfinder 2e
 - Module version: 4.4.2
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by ironmonk88** [comment]
I tried this on the Forge and the button to step away works to leave and return.

**Comment by ironmonk88** [comment]
Closing this as I can't replicate and it's been open for awhile.
