### ISSUE TITLE
Deprecation warnings with Chat Commander

### ISSUE THREAD

**Issue by DJ4ddi** [ironmonk88/breaktime#24]
**Problem**
This module uses the old Chat Command Library API, which was deprecated in version 2.0.0. This results in numerous deprecation warnings, as reported in https://gitlab.com/woodentavern/foundryvtt-chat-command-lib/-/issues/2.

Existing functionality should still work, so this is not an urgent issue.

**Solution**
Please update the module to use the newer API. The [changelog](https://gitlab.com/woodentavern/foundryvtt-chat-command-lib/-/blob/master/CHANGELOG.md) contains a rough overview over the changes and new features that you might want to use.

**Additional context**
If you need any help migrating to the new API, feel free to contact me directly on Discord `@DJ Addi#1087`.

**Comment by ironmonk88** [comment]
Fixed in the latest version.  Thank you.
