### ISSUE TITLE
[BUG] having to double click return before it registers you have returned.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [ironmonk88/breaktime#25]
**Describe the bug**
having to click return twice before it says your back.
**To Reproduce**
1. Go to button the left hand side.
2. . Click on button to step away
3. Scroll down to see that it has been pressed twice for it to respond

**Expected behavior**
press once for returning rather than twice

**Screenshots**
![image](https://user-images.githubusercontent.com/62528192/231878402-a11484ea-7ebb-459a-a751-629aea9a5444.png)

**Please complete as much of the following information as possible:**
 - Browser [e.g. chrome, safari] firefox
 - Foundry Version [e.g. v9] v10.249
 - System [e.g. D&D5e, Pathfinder 2e] pf2
 - Module version
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by ironmonk88** [comment]
Fixed in the latest release.
