### ISSUE TITLE
Allow for "elevator" music.

### ISSUE THREAD

**Issue by Oryan77** [ironmonk88/breaktime#27]
I tried to swap out the audio with a new mp3 song thinking that the song would end when the break was over. The song keeps playing if the break ends sooner than the song does. The song only ends when it finishes playing.

I misunderstood the intention of changing the audio, but I think playing a song while on break can help keep a particular mood going. Turning off the audio when the break is over and allowing players to mute the audio on their end during the break would be a nice addition.

**Comment by ironmonk88** [comment]
Added in the latest release.
