### ISSUE TITLE
[BUG] Button appears twice in Player list in COC7 game system

### ISSUE THREAD

**Issue by farling42** [ironmonk88/breaktime#29]
**Describe the bug**
The button appears twice in the button list for the COC7 game syste

**To Reproduce**

**Expected behavior**
COC7 has added an extra field into the Players list, so maybe this is messing with the placement logic.

**Screenshots**
![image](https://github.com/ironmonk88/breaktime/assets/17485384/d2639891-f0bb-4c49-89c6-5787360811db)

**Please complete as much of the following information as possible:**
 - Browser: Chrome
 - Foundry Version: 11.301
 - System: coc7 0.10.4
 - Module version: 11.01
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
