### ISSUE TITLE
Having issues with the chat commands

### ISSUE THREAD

**Issue by dumplingmon** [ironmonk88/breaktime#3]
Command"/brb" isn't working in my worlds using the DND 5e and Call of Cthulhu 7th Edition (unofficial) frameworks. I tried deactivating all other modules as well.

**Comment by ironmonk88** [comment]
Did you install the chat command library?

**Comment by dumplingmon** [comment]
Yes, I figured out that was the problem last week but forgot to put an update here. Sorry!On May 24, 2021 19:43, ironmonk88 ***@***.***> wrote:
Did you install the chat command library?
