### ISSUE TITLE
Option to add a sound to play on break.  Like hold music

### ISSUE THREAD

**Issue by WizardForHire123** [ironmonk88/breaktime#30]
**Is your feature request related to a problem? Please describe.**
I want to have it play hold music when a break is triggered cuz I think it’d be moderately funny. 
I recognize this is stupid and feel free to ignore :)
Could also be a feature of sound enhancement or a Matt trigger. Again I know its dumb and feel free to ignore

**Comment by ironmonk88** [comment]
Added to the latest release.
