### ISSUE TITLE
[BUG] Breaktime does not send notification to Chat, Sound playlists are not showing in selection.

### ISSUE THREAD

**Issue by CelestianGC** [ironmonk88/breaktime#37]
**Describe the bug**
Breaktime does not send notification to Chat, Sound playlists are not showing in selection.

**To Reproduce**
1. Make sure Notification "Chat" set.
2. Click on "Breaktime" from top left list of icons on Foundry desktop to step away
3. Icon shows on Game user on bottom left panel but no chat output is shown.
4. Ensure that system has Playlists in the World.
5. Configure Break Time, Select the "Breaktime Playlist" (there will be no playlists available).

**Expected behavior**
Chat message should be shown when a player clicks the breaktime icon to indicate they step away.
Breaktime configuration "Breaktime Playlist" should show list of available playlists to use.

**Screenshots**
![image](https://github.com/ironmonk88/breaktime/assets/3953802/67177976-3580-428a-b1d4-7749c527073c)

![image](https://github.com/ironmonk88/breaktime/assets/3953802/00303cd2-e523-4a2b-802c-d8c90edec255)

**Please complete as much of the following information as possible:**
 - Browser Native application (electron)
 - Foundry Version v12 324
 - System D&D5e
 - Module version 12.01
 - Are there any errors in the console [e.g. press F12 and look for red text]
 When toggling "break"
 
![image](https://github.com/ironmonk88/breaktime/assets/3953802/a1ad7446-e325-4b77-81c7-cf9b54e75eed)

 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.
No other modules loaded.

**Additional context**
NA.

**Comment by CelestianGC** [comment]
Thanks for sorting out the chat message alert.

Hopefully the playlist selection can be resolved. My guys seem to like the "away" music for some reason.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
