### ISSUE TITLE
[BUG] cant select breaktime play list. it shows as blank

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [ironmonk88/breaktime#41]
**Describe the bug**
when you click the drop down menu for the breaktime play lists it doesnt display the available playlists.

**To Reproduce**
1. Go to  play lists for breaktime in the settings
2. Click on click on drop down menu

**Expected behavior**
i expected the drop down menu to display the available play lists.

**Screenshots**
![chrome_4YOhVZtjKb](https://github.com/ironmonk88/breaktime/assets/62528192/70f7a55a-e559-4a0d-8a46-87cb1c989eae)

**Please complete as much of the following information as possible:**
 - Foundry Version [e.g. v9] v12
 - System [e.g. D&D5e, Pathfinder 2e] pf2e 
 - Module version latest
 - Are there any errors in the console [e.g. press F12 and look for red text]
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction.

**Additional context**

**Comment by roi007leaf** [comment]
Yup, same here

**Comment by Randomisation** [comment]
Same issue here

**Comment by Ravingdork** [comment]
Came here to report the same issue.

**Comment by Leones5x5** [comment]
This is still broken

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
