### ISSUE TITLE
[BUG] Beak Time sfx play when they shouldn't

### ISSUE THREAD

**Issue by Ravingdork** [ironmonk88/breaktime#44]
**Describe the bug**
When we used Break Time, then turned it off at the end of the break players and the GM complained about hearing the Break Sound sfx (a ticking clock in our case) even when Break Time was over and turned off. There appeared to be no way to stop the continuous sfx short of the individual participants refreshing their respective browser windows.

**To Reproduce**
1. Go to Break Time settings and set a Break Sound.
2. Start a game and initiate Break Time.
3. End Break Time and close out any related dialog windows.
4. Listen for the sound effect to start up, or persist.

**Expected behavior**
For there to be no module sfx at all once the Break Time is ended and closed out.

**Please complete as much of the following information as possible:**
 - Brave
 - Foundry Version v12
 - Pathfinder 2e
 - Module version 12.02

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
