### ISSUE TITLE
[BUG] Auto-Start Timer prevents Break on Clients due to Permission Error

### ISSUE THREAD

**Issue by zero127** [ironmonk88/breaktime#45]
**Describe the bug**
When Auto-start Break Timer is set, break will not start for anyone but GM. A permission error is displayed to non-gm users.

**To Reproduce**
1. Enable Breaktime
2. In settings, configure a break sound, and break end sound, set time to a time (i have mine 5m), and set Checkbox setting for break to auto start to checked.
3. Start a break with at least one connected client. 
4. Break only starts for GM, users do not hear sounds, and see a permission error

**Expected behavior**
Break behaves as normal, but the timer starts. 

**Screenshots**
n/a, the issue is that one setting. With it off, the module functions perfectly.

**Please complete as much of the following information as possible:**
 - Browser Locally hosted Foundry (gm), Chrome (player)
 - Foundry Version 12.331
 - System D&D5e v3.3.1
 - V 12.02 
 - Console Errors? Strangely, no console error to be found on this. But it is a visual warning displayed to the user (the top pop-up)
 - Tried FTC? Yes, reproduction occurs with only this module enabled for me.

**Additional context**
Low priority issue for me as i don't "need" the thing to start automatically, but it would be cool. Just reporting for due diligence since i found it and troubleshot it. :) -- its by no means game-breaking for me.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
