### ISSUE TITLE
Change Key Bind?

### ISSUE THREAD

**Issue by Heljspe** [ironmonk88/breaktime#5]
Might just be my typing, or a bit of lag, but triggering on Shift+Space often triggers when I don't want it to. We type a lot and its getting so annoying I've considered turning the module off. :( 
Would love an option to trigger with a different keybind (Crtl+Space?) or even just with a button or macro instead of a keybind? :)

**Comment by ironmonk88** [comment]
Added the option to change the hot key that activates it.
Had to change the activation key to Shift+Home.
