### ISSUE TITLE
[Bug] BreakTIme status restarts after a few seconds

### ISSUE THREAD

**Issue by szefo09** [ironmonk88/breaktime#7]
Hey, after recent updates I've noticed that after my player clicks: "I'm back", the status sets to ready, and then after a few seconds it goes back to "Away". 
Anyway for You to investigate this behavior?

**Comment by Kurrgan** [comment]
I have this problem as well, except as a GM it shows that they are ready as intended, but for my player they see themselves revert to "Away"
