### ISSUE TITLE
It looks like 1.0.9 removed shift+space functionality

### ISSUE THREAD

**Issue by dmrickey** [ironmonk88/breaktime#9]
Space is pause. Shift+space is pause with the extra window that pops up. Why doesn't this work anymore?

**Comment by dmrickey** [comment]
Thanks. I wasn't trying to be difficult, just verbose in my thought process. I thank you for taking your time to add in a workaround to get the old functionality back

**Comment by ironmonk88** [comment]
Closing this as I think the functionality was satisfied.
